---
kind: pipeline
name: node-latest

steps:
- name: db-setup
  image: mysql
  commands:
  - sleep 30
  - while ! mysqladmin ping -h database -u drone -pdrone --silent; do sleep 1; done
  - mysql -h database -u drone -pdrone -e "CREATE TABLE IF NOT EXISTS drone_db.pipelines (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(50) NOT NULL);"

- name: test
  image: node:latest
  commands:
  - npm install
  - npm test
  env:
  - NODE_ENV=test
  - NODE_PORT=3306
  - NODE_HOST=localhost
  - NODE_DB_PORT=3306
  ports:
  - 3306


services:
- name: database
  image: mysql
  ports:
  - 3306
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: helpyadb

---
kind: pipeline
name: node14

steps:
- name: test
  image: node:14
  commands:
  - npm install
  - npm test

...