---
kind: pipeline
name: node-latest

steps:
- name: test
  image: node:latest
  commands:
  - npm install
  - mysql -u root -h localhost -p Cosc499api
  - npm test

services:
- name: database
  image: mysql
  environment:
    MYSQL_DATABASE: helpyadb
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

---
kind: pipeline
name: node14

steps:
- name: test
  image: node:14
  commands:
  - npm install
  - npm test

...