---
kind: pipeline
name: node12

steps:
- name: test
  image: node:12.10.0/mysql
  commands:
  -npm install
  - sleep 15
  - mysql -u root -h database --execute="SELECT VERSION();"

services:
- name: database
  image: mysql
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: test
---
kind: pipeline
name: node14

steps:
- name: test
  image: node:14
  commands:
  - npm install
  - npm test

...