---
kind: pipeline
name: database

steps:
- name: db-setup
  image: mysql:latest
  commands:
  - sleep 30
  - mysql -u root -h database --execute="ALTER USER 'root'@'database' IDENTIFIED WITH mysql_native_password BY 'password';"
  - mysql -u root -h database --execute="SELECT VERSION();"
  - mysql -u root -p password -h database --execute="CREATE DATABASE IF NOT EXISTS heroku_b5b309c959adca7"
  # - mysql -u root -h database --execute="CREATE USER 'be51542c7ae965'@'database' IDENTIFIED BY '8fbdc8b3';"
  # - mysql -u root -h database --execute="GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER ON *.* TO 'be51542c7ae965'@'database' WITH GRANT OPTION;"
  # - mysql -u root -h database --execute="SELECT host,user,authentication_string FROM mysql.user"
  - mysql -u root -p password -h database heroku_b5b309c959adca7 < database.sql
  # - mysql -u root -h database --execute="SHOW DATABASES;"

- name: test
  image: node:latest
  commands:
  - npm install
  # - node dbdiagnostic.js
  - npm test

services:
- name: database
  image: mysql:latest
  ports:
  - 3306
  environment:
    MYSQL_DATABASE: heroku_7d45a1c09c1d741
    MYSQL_USER: be51542c7ae965
    MYSQL_PASSWORD: 8fbdc8b3
    MYSQL_ROOT_PASSWORD: password
    MYSQL_Grant: SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER ON *.* TO 'be51542c7ae965'@'database' WITH GRANT OPTION

---
kind: pipeline
name: node14

steps:
- name: test
  image: node:14
  commands:
  - npm install
  - npm test

...