---
kind: pipeline
name: node-latest

steps:
- name: db-setup
  image: mysql
  commands:
  - sleep 30
  - mysql -u root -h database --execute="SELECT VERSION();"
  - mysql -u root -h database --execute="CREATE DATABASE IF NOT EXISTS helheroku_7d45a1c09c1d741pyadb"
  - mysql -u root -h database --execute="CREATE USER 'be51542c7ae965'@'localhost' IDENTIFIED BY '8fbdc8b3';"
  - mysql -u root -h database --execute="GRANT CREATE, ALTER, DROP, INSERT, UPDATE, DELETE, SELECT, REFERENCES, RELOAD on *.* TO 'be51542c7ae965'@'lcoalhost' WITH GRANT OPTION;"
  - mysql -u root -h database --execute="SELECT host,user,authentication_string FROM mysql.user"
  - mysql -u root -h database heroku_7d45a1c09c1d741 < database.sql

- name: test
  image: node:latest
  commands:
  - npm install
  - netstat -a | more
  - npm test

services:
- name: database
  image: mysql
  ports:
  - 8080
  environment:
     MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

---
kind: pipeline
name: node14

steps:
- name: test
  image: node:14
  commands:
  - npm install
  - npm test

...