---
kind: pipeline
name: node-latest

steps:
- name: db-setup
  image: mysql
  commands:
  - sleep 30
  - mysql -u root -h database --execute="SELECT VERSION();"

- name: test
  image: node:latest
  commands:
  - npm install
  - npm test

services:
- name: database
  image: mysql
  ports:
  - 3306
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: test
...