---
kind: pipeline
name: node-latest

steps:
- name: test
  image: node:latest
  commands:
  - npm install
  - npm test

services:
- name: database
  image: mysql:latest
  environment:
    MYSQL_DATABASE: helpyadb
    MYSQL_USER: root
    MYSQL_PASSWORD: Cosc499api
    MYSQL_ROOT_PASSWORD: Cosc499api
    MYSQL_ROOT_HOST: local
    MYSQL_ROOT_PORT: 8080
    MySQL_PORT: 3306

---
kind: pipeline
name: node14

steps:
- name: test
  image: node:14
  commands:
  - npm install
  - npm test

...