---
kind: pipeline
name: node12

steps:
- name: test
  image: node:12.x
  commands:
  - npm install
  - npm test

---
kind: pipeline
name: node14

steps:
- name: test
  image: node:14.x
  commands:
  - npm install
  - npm test

...