---
kind: pipeline
type: docker
name: node-latest

steps:
  - name: db-setup
    image: docker/compose:1.29.2
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker-compose -f drone-compose.yml up

  - name: test
    image: node:latest
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    expose:
      - "8080"
    commands:
      - npm install
      - npm test
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
