---
kind: pipeline
name: node12

steps:
- name: test
  image: docker
  commands:
  - docker-compose -f docker-compose.yml up -d
  - npm test

---
kind: pipeline
name: node14

steps:
- name: test
  image: node:14
  commands:
  - npm install
  - npm test

...