---
kind: pipeline
name: node-latest

steps:
- name: db-setup
  image: mysql
  commands:
  - sleep 30
  - mysql -u root -h database --execute="SELECT VERSION();"
  - mysql -u root -h database --execute="CREATE DATABASE IF NOT EXISTS helpyadb"
  - mysql -u root -h database --execute="CREATE USER 'be51542c7ae965'@'ip-10-0-3-24.ec2.internal';"
  - mysql -u root -h database --execute="GRANT ALL PRIVILEGES ON *.* TO 'be51542c7ae965'@'ip-10-0-3-24.ec2.internal';"
  - mysql -u root -h database --execute="SELECT user,host,password FROM mysql.user;"
  - mysql -u root -h database helpyadb < database.sql

- name: test
  image: node:latest
  commands:
  - npm install
  - netstat -a | more
  - npm test

services:
- name: database
  image: mysql
  ports:
  - 8080
  environment:
     MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

---
kind: pipeline
name: node14

steps:
- name: test
  image: node:14
  commands:
  - npm install
  - npm test

...