---
kind: pipeline
name: database

steps:
- name: db-setup
  image: mysql:5.7
  commands:
  - while ! mysqladmin ping -h database -u root --silent; do sleep 1; done
  - mysql -u root -h database --execute="CREATE USER 'b734bbe733ac95'@'database' IDENTIFIED BY '23fc955b';"
  - mysql -u root -h database --execute="GRANT ALL PRIVILEGES ON *.* TO 'b734bbe733ac95'@'%' WITH GRANT OPTION;"
  # - mysql -u root -h database --execute="ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'password';"
  # - mysql -u root -h database --execute="SELECT VERSION();"
  - mysql -u root -h database --execute="CREATE DATABASE IF NOT EXISTS heroku_b5b309c959adca7"
  # - mysql -u root -h database --execute="CREATE USER 'b734bbe733ac95'@'database' IDENTIFIED BY '23fc955b';"
  # - mysql -u root -h database --execute="GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER ON *.* TO 'b734bbe733ac95'@'database' WITH GRANT OPTION;"
  # - mysql -u root -h database --execute="SELECT host,user,authentication_string FROM mysql.user"
  - mysql -u root -h database heroku_b5b309c959adca7 < database.sql
  - mysql -u root -h database heroku_b5b309c959adca7 < testing_with_all_tables.txt
  # - mysql -u root -h database --execute="SHOW GRANTS FOR 'b734bbe733ac95'@'%';"
  # - mysql -u root -h database --execute="SHOW DATABASES;"
  - mysql -u root -h database --execute="FLUSH PRIVILEGES;"

- name: test
  image: node:latest
  commands:
  - npm config rm proxy 
  - npm config rm https-proxy --tried removing npm proxy 
  - npm ci
  # - node dbdiagnostic.js
  - npm test
  
-environment:
  NODE_ENV: test
  PORT: 3306
  DB_HOST: database
  DB_USER: b734bbe733ac95
  DB_PASSWORD: 23fc955b
  DB_NAME: heroku_b5b309c959adca7

services:
- name: database
  image: mysql:latest
  ports:
  - 3306
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: yes
    MYSQL_USER: b734bbe733ac95
    MYSQL_PASSWORD: 23fc955b
    MYSQL_Grant: SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER ON *.* TO 'b734bbe733ac95'@'database' WITH GRANT OPTION

# ---
# kind: pipeline
# name: node14

# steps:
# - name: test
#   image: node:14
#   commands:
#   - npm install
#   - npm test

...