version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    expose:
      - 8080
    volumes:
      - ./server.js:/app/app/server.js
      - ./app:/app/app
volumes: 
  db: