version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    expose:
      - "8080"
    volumes:
      - ./server.js:/app/app/server.js
      - ./app:/app/app
      - '/app/node_modules'

    mysql_server:
      image: mysql:latest
      restart: unless-stopped
      env_file: ./.env
      expose:
        - "3306"
      volumes:
        - db:/var/lib/mysql
        - .:/app
      env_file: ./.env