name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    services:
      mysql:
        image: mysql:5.7
        env:
          DB_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: password
          DB_USER: b734bbe733ac95
          DB_PASSWORD: 23fc955b
          DB_NAME: heroku_b5b309c959adca7
          port: 3306
          MYSQL_Grant: SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER ON *.* TO 'b734bbe733ac95'@'12.0.0.1' WITH GRANT OPTION

        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm install
          sudo service mysql start
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword  -e "CREATE USER 'b734bbe733ac95'@'127.0.0.1' IDENTIFIED BY '23fc955b';"
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword  -e "SELECT host,user,authentication_string FROM mysql.user"
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword  -e "CREATE DATABASE IF NOT EXISTS heroku_b5b309c959adca7"
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword  -e "GRANT ALL PRIVILEGES ON *.* TO 'b734bbe733ac95'@'127.0.0.1' IDENTIFIED BY '23fc955b' WITH GRANT OPTION;"
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword  -e "SHOW DATABASES"
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword  -e "SHOW GRANTS"
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -Dheroku_b5b309c959adca7 < database.sql
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -Dheroku_b5b309c959adca7 < testing_with_all_tables.txt
          npm test
        env:
          CI: true
          DB_HOST: 127.0.0.1
          DB_USER: b734bbe733ac95
          DB_PASSWORD: 23fc955b
          DB_NAME: heroku_b5b309c959adca7
          port: 3306
          DB_Grant: SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER ON *.* TO 'b734bbe733ac95'@'database' WITH GRANT OPTION

